version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: id
            tests:
              - unique
              - not_null

          - name: status
            tests:
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

          - name: user_id
            tests:
              - not_null
              - relationships:
                  to: source('jaffle_shop', 'customers')
                  field: id

  - name: stripe
    database: raw
    loaded_at_field: _batched_at
    loader: airflow     # this is just for documentation
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: payment
        columns:
          - name: id
            tests:
              - not_null
              - unique

          - name: paymentmethod
            tests:
              - accepted_values:
                  values:
                    - bank_transfer
                    - coupon
                    - credit_card
                    - gift_card
